package de.verdox.mccreativelab.impl.vanilla.pack;

import de.verdox.mccreativelab.generator.AssetPath;
import de.verdox.mccreativelab.generator.ResourcePackFileHoster;
import de.verdox.mccreativelab.generator.resourcepack.CustomResourcePack;
import de.verdox.mccreativelab.impl.vanilla.platform.NMSPlatform;
import de.verdox.mccreativelab.platform.GeneratorPlatformHelper;
import de.verdox.mccreativelab.platform.PlatformResourcePack;

import java.io.File;
import java.io.IOException;

public class ResourcePackManager {
    private CustomResourcePack customResourcePack;
    private GeneratorPlatformHelper helper;
    private ResourcePackFileHoster resourcePackFileHoster;

    public void init(NMSPlatform nmsPlatform) throws IOException {
        File templateFolder = new File("/ressourcePack/template/");
        File fileStorage = new File("/ressourcePack/settings/");
        File hostStorage = new File("/ressourcePack/host/");
        templateFolder.mkdirs();
        fileStorage.mkdirs();
        this.customResourcePack = new CustomResourcePack("mcc", 18, "Generated by MCCreativeLab", AssetPath.buildPath("resourcePacks"), templateFolder, fileStorage);
        this.helper = nmsPlatform.constructPackGeneratorHelper(customResourcePack);
        this.resourcePackFileHoster = new ResourcePackFileHoster(hostStorage);
        PlatformResourcePack.INSTANCE.setup(this.customResourcePack, rp -> {});
    }

    public void buildPack() {
        try {
            customResourcePack.installPack(false);
            resourcePackFileHoster.createResourcePackZipFiles();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public CustomResourcePack getResourcePack() {
        return customResourcePack;
    }

    public GeneratorPlatformHelper getHelper() {
        return helper;
    }

    public ResourcePackFileHoster getResourcePackFileHoster() {
        return resourcePackFileHoster;
    }
}
